### ISSUE TITLE
Stolen artwork, designs, and assets

### ISSUE THREAD

**Issue by jacksonisiah** [osuawasu/awasu-web#1]
![image](https://user-images.githubusercontent.com/34609781/55272632-30a31e00-52b7-11e9-9d3c-4396d2c5b2a3.png)

i'm sorry, what is this blatant fucking copy and can you come up with something at least original for fucking once?

legitimate issue because this is copyrighted assets you are using here and peppy can DMCA you out the ass.

**Comment by ilytt** [comment]
ight
